on:
  push:
    branches: 
      main


jobs:
  build:
    name: build(linux, android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          version: stable
      - name: install flutter
        run: |
          snap install flutter --classic
          
      - name: build linux
        run: |
          flutter build linux --release
          
      - name: build apk
        run: |
          flutter build apk --release
