on:
  push:
    branches: 
      main


jobs:
  build:
    name: build(linux, android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: install flutter
        run: |
          sudo snap install flutter --classic
          
      - name: install deps
        run: |
          flutter pub get
          chmod +x ./gen.sh
          ./gen.sh
          
      # - name: build linux
      #  run: |
      #    flutter build linux --release
          
      - name: build apk
        run: |
          flutter build apk --release
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            # build/app/outputs/linux/
