on:
  push:
    branches: 
      main


jobs:
  build:
    name: build(windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3.1.0
      - uses: britannio/action-install-flutter@v1.1
        with:
          version: stable
      - shell: | 
          flutter doctor
          flutter build -h
