on:
  push:
    branches: 
      main


jobs:
  build:
    name: build(linux, android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          version: stable
      - name: install dependencies
        uses: geowatson/flutter-latest@1.0.0
        with:
          args: pub get
          
      - name: build linux
        uses: geowatson/flutter-latest@1.0.0
        with:
          args: build linux --release
          
      - name: build apk
        uses: geowatson/flutter-latest@1.0.0
        with:
          args: build apk --release
